language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install --dev --prefer-source
    - mkdir -p web/code-coverage

script:
    - vendor/bin/atoum

notifications:
    email:
        recipients:
            - ci@verylastroom.com
        on_success: change
        on_failure: change
